-- QUERY: Table structure for table 'reviews'
CREATE TABLE IF NOT EXISTS public.reviews (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    review_rating integer NOT NULL,
    review_text VARCHAR(255) NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION
);